module.exports = {
  GET_TASK_DETAIL: 'GET_TASK_DETAIL',
  GET_ORDERS: 'GET_ORDERS',
  GET_FINISHED_ORDERS: 'GET_FINISHED_ORDERS',
  GET_HISTORY: 'GET_HISTORY',
  UPDATE_DRIVER_STATUS:'UPDATE_DRIVER_STATUS',
  CANCEL_NOTIFICATION: 'CANCEL_NOTIFICATION',
  UPDATE_SINGLE_ORDER: 'UPDATE_SINGLE_ORDER',
};
